AllCops:
  TargetRubyVersion: 2.5
  Exclude:
  - 'bin/**/*'
  - 'vendor/**/*'
  - 'db/migrate/2017*'
  DisplayCopNames: true

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/ExtraSpacing:
  AllowForAlignment: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 40

Metrics/BlockNesting:
  Max: 4

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Max: 500

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 500

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatString:
  EnforcedStyle: sprintf

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/MutableConstant:
  Enabled: true

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/ParenthesesAroundCondition:
  AllowSafeAssignment: false

Style/OptionHash:
  Enabled: true
  Exclude:
  - 'spec/factories/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: '()'
    '%w': '()'

Style/Send:
  Enabled: true

Style/SignalException:
  EnforcedStyle: semantic

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Rails:
  Enabled: true

Rails/Date:
  EnforcedStyle: flexible

Rails/FindEach:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/OutputSafety:
  Enabled: false

Rails/TimeZone:
  EnforcedStyle: flexible
